version: 0.0
os: linux
files:
  - source: /
    destination: /opt/barra
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      runas: root
  # AfterInstall:
  #   - location: scripts/install_deps.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root
